export default {
    products: [
        {
            _id: '000000000000000000000001',
            name: 'Italian Sausage',
            region: 'Marche',
            image: './images/product-1.jpg',
            price: 8.15,
            brand: 'Tomassoni',
            rating: 4.7,
            numReviews: 100,
            countInStock: 1000,
            description:'Deliceus italian sausage',
        },
        {
            _id: '000000000000000000000002',
            name: 'Mozzarella di bufala',
            region: 'Campania',
            image: './images/product-2.jpg',
            price: 16,
            brand: 'La Fattoria - Battipaglia',
            rating: 4.1,
            numReviews: 100,
            countInStock: 1000,
            description:'Traditional Mozzarella for pizza, salads and more',
        },
        {
            _id: '000000000000000000000003',
            name: 'Piadina Romagnola',
            region: 'Emilia Romagna',
            image: './images/product-3.jpg',
            price: 5,
            brand: 'La Piadina del Chiosco',
            rating: 4.5,
            numReviews: 100,
            countInStock: 1000,
            description:'Deliceus italian sausage',
        },
        {
            _id: '000000000000000000000004',
            name: 'Tartufo nero',
            region: 'Umbria',
            image: './images/product-4.jpg',
            price: 1500,
            brand: 'Tartuferia',
            rating: 5,
            numReviews: 100,
            countInStock: 1000,
            description:'Eco, vegan, hand-harvested black truffle',
        },
        {
            _id: '000000000000000000000005',
            name: 'Rosso Conero red Wine',
            region: 'Marche',
            image: './images/product-5.jpg',
            price: 13,
            brand: 'Cantine Angeli di Varano',
            rating: 4.6,
            numReviews: 100,
            countInStock: 1000,
            description:'Red wine from the regions of Marche, Italy',
        },
        {
            _id: '000000000000000000000006',
            name: 'Italian Olive Oil',
            region: 'Toscana',
            image: './images/product-6.jpg',
            price: 9,
            brand: 'Del Rebene',
            rating: 4.8,
            numReviews: 100,
            countInStock: 1000,
            description:'Olive Oil made from true italian olives',
        },
        {
            _id: '000000000000000000000007',
            name: 'Mexican chipotle chili',
            region: 'Puebla',
            image: './images/product-7.webp',
            price: 4,
            brand: 'La Costeña',
            rating: 4.3,
            numReviews: 100,
            countInStock: 1000,
            description:'Deliceus canned chipotle chilies for sauces, tacos, sandwiches and more',
        },
        {
            _id: '000000000000000000000008',
            name: 'Handmade Tortillas (1kg)',
            region: 'Puebla',
            image: './images/product-8.jpg',
            price: 3,
            brand: 'Doña Mary',
            rating: 4.9,
            numReviews: 100,
            countInStock: 1000,
            description:'Handmade tortillas from mexico',
        },
        {
            _id: '000000000000000000000009',
            name: 'Oaxaca Cheese (1kg)',
            region: 'Oaxaca',
            image: './images/product-9.webp',
            price: 7,
            brand: 'Real de Oaxaca',
            rating: 4.6,
            numReviews: 100,
            countInStock: 1000,
            description:'Artisan Oaxacan cheese made by Indigenous people from Oaxaca, Mexico',
        },
        {
            _id: '000000000000000000000010',
            name: 'Salsa macha',
            region: 'Naucalpan de Juárez',
            image: './images/product-10.jpg',
            price: 5.99,
            brand: 'Tía de Andoni',
            rating: 4.8,
            numReviews: 100,
            countInStock: 1000,
            description:'Deliceus Chili sauce made by Andonis aunt, its a family recipe',
        },
        {
            _id: '000000000000000000000011',
            name: 'Refried black beans',
            region: 'Veracruz',
            image: './images/product-11.jpg',
            price: 3.99,
            brand: 'Isadora',
            rating: 4.4,
            numReviews: 100,
            countInStock: 1000,
            description:'Versatile and long lasting refried beans, base for many mexican dishes',
        },
        {
            _id: '000000000000000000000012',
            name: 'Mole Poblano',
            region: 'Puebla',
            image: './images/product-12.jpg',
            price: 12.99,
            brand: 'Doña María',
            rating: 4.9,
            numReviews: 100,
            countInStock: 1000,
            description:'Traditional and rich Mole Poblano',
        },
        {
            _id: '000000000000000000000013',
            name: 'Aceite de Oliva Virgen Extra',
            region: 'Córdoba',
            image: './images/product-13.jpg',
            price: 7.55,
            brand: 'Los Omeya',
            rating: 5.0,
            numReviews: 100,
            countInStock: 1000,
            description:'Olive oil from real spanish olives',
        },
        {
            _id: '000000000000000000000014',
            name: 'ColaCao',
            region: 'National',
            image: './images/product-14.jpg',
            price: 3.29,
            brand: 'ColaCao',
            rating: 4.5,
            numReviews: 100,
            countInStock: 1000,
            description:'Powdered chocolate for kids and adults',
        },
        {
            _id: '000000000000000000000015',
            name: 'Fresas caja 2kg',
            region: 'Huelva',
            image: './images/product-15.jpeg',
            price: 2.88,
            brand: 'Marifrancis',
            rating: 4.2,
            numReviews: 100,
            countInStock: 1000,
            description:'Bio strawberries',
        },
        {
            _id: '000000000000000000000016',
            name: 'Pulpo gallego 0.5kg',
            region: 'Galicia',
            image: './images/product-16.png',
            price: 19.80,
            brand: 'Bacalao de mar',
            rating: 4.8,
            numReviews: 100,
            countInStock: 1000,
            description:'Freshly caught octopus from the region of Galicia',
        },
        {
            _id: '000000000000000000000017',
            name: 'Vino fino Eléctrico',
            region: 'Córdoba',
            image: './images/product-17.jpg',
            price: 18.50,
            brand: 'Bodegas Toro Albalá',
            rating: 4.7,
            numReviews: 100,
            countInStock: 1000,
            description:'Deliceus wine from the region of Cordoba',
        },
        {
            _id: '000000000000000000000018',
            name: 'Jamón Ibérico de bellota',
            region: 'National',
            image: './images/product-18.jpg',
            price: 680,
            brand: 'Aljomar',
            rating: 5.0,
            numReviews: 100,
            countInStock: 1000,
            description:'Luxurious Iberian Jam from hasselnussed fed pork',
        },
    ],
};