module.exports = {
    products: [
        {
            _id: '1',
            name: 'Italian Sausage',
            region: 'Marche',
            image: './images/product-1.jpg',
            price: 8.15 + ' (perKg)',
            brand: 'Tomassoni',
            rating: 4.7,
            numReviews: 100,
            countInStock: 1000,
        },
        {
            _id: '2',
            name: 'Mozzarella di bufala',
            region: 'Campania',
            image: './images/product-2.jpg',
            price: 16 + ' (perKg)',
            brand: 'La Fattoria - Battipaglia',
            rating: 4.1,
            numReviews: 100,
            countInStock: 1000,
        },
        {
            _id: '3',
            name: 'Piadina Romagnola',
            region: 'Emilia Romagna',
            image: './images/product-3.jpg',
            price: 5,
            brand: 'La Piadina del Chiosco',
            rating: 4.5,
            numReviews: 100,
            countInStock: 1000,
        },
        {
            _id: '4',
            name: 'Tartufo nero',
            region: 'Umbria',
            image: './images/product-4.jpg',
            price: 1500 + ' (perKg)',
            brand: 'Tartuferia',
            rating: 5,
            numReviews: 100,
            countInStock: 1000,
        },
        {
            _id: '5',
            name: 'Rosso Conero red Wine',
            region: 'Marche',
            image: './images/product-5.jpg',
            price: 13,
            brand: 'Cantine Angeli di Varano',
            rating: 4.6,
            numReviews: 100,
            countInStock: 1000,
        },
        {
            _id: '6',
            name: 'Italian Olive Oil',
            region: 'Toscana',
            image: './images/product-6.jpg',
            price: 9,
            brand: 'Del Rebene',
            rating: 4.8,
            numReviews: 100,
            countInStock: 1000,
        },
        {
            _id: '7',
            name: 'Mexican chipotle chili',
            region: 'Puebla',
            image: './images/product-7.webp',
            price: 4,
            brand: 'La Costeña',
            rating: 4.3,
            numReviews: 100,
            countInStock: 1000,
        },
        {
            _id: '8',
            name: 'Handmade Tortillas (1kg)',
            region: 'Puebla',
            image: './images/product-8.jpg',
            price: 3,
            brand: 'Doña Mary',
            rating: 4.9,
            numReviews: 100,
            countInStock: 1000,
        },
        {
            _id: '9',
            name: 'Oaxaca Cheese (1kg)',
            region: 'Oaxaca',
            image: './images/product-9.webp',
            price: 7,
            brand: 'Real de Oaxaca',
            rating: 4.6,
            numReviews: 100,
            countInStock: 1000,
        },
        {
            _id: '10',
            name: 'Salsa macha',
            region: 'Naucalpan de Juárez',
            image: './images/product-10.jpg',
            price: 5.99,
            brand: 'Tía de Andoni',
            rating: 4.8,
            numReviews: 100,
            countInStock: 1000,
        },
        {
            _id: '11',
            name: 'Refried black beans',
            region: 'Veracruz',
            image: './images/product-11.jpg',
            price: 3.99,
            brand: 'Isadora',
            rating: 4.4,
            numReviews: 100,
            countInStock: 1000,
        },
        {
            _id: '12',
            name: 'Mole Poblano',
            region: 'Puebla',
            image: './images/product-12.jpg',
            price: 12.99,
            brand: 'Doña María',
            rating: 4.9,
            numReviews: 100,
            countInStock: 1000,
        },
    ],
};