export default {
    products: [
        {
            _id: '1',
            names: 'Italian Sausage',
            region: 'Marche',
            image: '/images/product-1.jpg',
            pricePerKg: 8.15,
            brand: 'Tomassoni',
            rating: 4.7,
            numReviews: 100,
            countInStock: 1000,
        },
        {
            _id: '2',
            names: 'Mozzarella di bufala',
            region: 'Campania',
            image: '/images/product-2.jpg',
            pricePerKg: 16,
            brand: 'La Fattoria - Battipaglia',
            rating: 4.1,
            numReviews: 100,
            countInStock: 1000,
        },
        {
            _id: '3',
            names: 'Piadina Romagnola',
            region: 'Emilia Romagna',
            image: '/images/product-3.jpg',
            price: 5,
            brand: 'La Piadina del Chiosco',
            rating: 4.5,
            numReviews: 100,
            countInStock: 1000,
        },
        {
            _id: '4',
            names: 'Tartufo nero',
            region: 'Umbria',
            image: '/images/product-4.jpg',
            pricePerKg: 1500,
            brand: 'Tartuferia',
            rating: 5,
            numReviews: 100,
            countInStock: 1000,
        },
        {
            _id: '5',
            names: 'Rosso Conero red Wine',
            region: 'Marche',
            image: '/images/product-5.jpg',
            price: 13,
            brand: 'Cantine Angeli di Varano',
            rating: 4.6,
            numReviews: 100,
            countInStock: 1000,
        },
        {
            _id: '6',
            names: 'Italian Olive Oil',
            region: 'Toscana',
            image: '/images/product-6.jpg',
            price: 9,
            brand: 'Del Rebene',
            rating: 4.8,
            numReviews: 100,
            countInStock: 1000,
        },
    ],
};